package com.scaj.db.scaj_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE FoodEntryBase PLEASE EDIT ../FoodEntry.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of FoodEntry object
 * 
 */
 
import org.bson.types.ObjectId;
import org.mongodb.morphia.annotations.Entity;
import java.util.Date;
import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;

import org.mongodb.morphia.annotations.Id;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import com.scaj.utils.ObjectIdListSerializer;


//IMPORT RELATIONS
import com.scaj.db.scaj_db.entity.User;

@Entity("FoodEntry")
public class FoodEntryBase {
	
	@Id
	@JsonSerialize(using = ToStringSerializer.class)
	private ObjectId _id;
	
	// Attributes
    private Integer Calorie;
    private Date Date;
    private String Name;
	
	
	// Relations _user
	@JsonSerialize(using = ToStringSerializer.class)
	private ObjectId _user;
	
	
	
	

    // GETTER AND SETTER
    
	public ObjectId get_id() {
		return _id;
	}

	public void set_id(ObjectId id) {
		this._id = id;
	}


	
	public Integer getCalorie() {
		return Calorie;
	}


	public void setCalorie(Integer Calorie) {
		this.Calorie = Calorie;
	}
    
	public Date getDate() {
		return Date;
	}


	public void setDate(Date Date) {
		this.Date = Date;
	}
    
	public String getName() {
		return Name;
	}


	public void setName(String Name) {
		this.Name = Name;
	}
    

	
    
    // Relations 1:m _user
	public ObjectId get_user() {
		return _user;
	}

	public void set_user(ObjectId _user) {
		this._user = _user;
	}
    
    
    
    
}