
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// FOODENTRY
export const CREATE_FOODENTRY_SUCCESS = "CREATE_FOODENTRY_SUCCESS";
export const DELETE_FOODENTRY_SUCCESS = "DELETE_FOODENTRY_SUCCESS";
export const GET_FOODENTRY_SUCCESS = "GET_FOODENTRY_SUCCESS";
export const LIST_FOODENTRY_SUCCESS = "LIST_FOODENTRY_SUCCESS";
export const UPDATE_FOODENTRY_SUCCESS = "UPDATE_FOODENTRY_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
